routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\Site\MainController;
Route::get('/', [MainController::class, 'index'])->name('main');

use App\Http\Controllers\Site\SinglePostController;
Route::get('show-post/{post_id}', [SinglePostController::class, 'index'])
    ->name('single_post');

use App\Http\Controllers\Site\AuthorPostsController;
Route::get('show-posts-author/{user_id}', [AuthorPostsController::class, 'index'])
    ->name('show_posts_author');

use App\Http\Controllers\Site\CategoryPostsController;
Route::get('show-posts-category/{category_id}', [CategoryPostsController::class, 'index'])
    ->name('show_posts_category');

use App\Http\Controllers\Site\SearchPostsController;
Route::get('search', [SearchPostsController::class, 'index'])->name('search');

use App\Http\Controllers\Site\ActivityUsersController;
Route::get('block_user/{post_id}', [ActivityUsersController::class, 'blockUser'])->name('block_user');

// -----------------------------------------------------------------------------
// First route verify
Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware('auth')->name('verification.notice');

// Second route verify
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/');
})->middleware(['auth', 'signed', 'addingRoleToUser:user'])->name('verification.verify');

// Third route verify
Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');
// -----------------------------------------------------------------------------

Route::middleware(['auth', 'verified', 'addingRoleToUser:user', 'role:admin|user'])
    ->get('/dashboard', function () {
    
    return view('dashboard');
})->name('dashboard');


Route::middleware(['auth', 'verified'])->group(function () {
    Route::resource('posts', App\Http\Controllers\PostController::class)
        ->middleware(['role:admin|user']);
    Route::resource('roles', App\Http\Controllers\RoleController::class);
    Route::resource('permissions', App\Http\Controllers\PermissionController::class);
    Route::resource('categories', App\Http\Controllers\CategoryController::class);
    Route::resource('users', App\Http\Controllers\UserController::class);
});

app/Http/Controllers/Site/ActivityUsersController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Flash;

/**
 * Class ActivityUsersController
 * @package App\Http\Controllers\Site
 */
class ActivityUsersController extends SiteController
{
    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function blockUser($id)
    {
        $user = User::findOrfail($id);

        if ($user->hasRole('admin')) {
            Flash::error('Admin cannot be banned.');

            return $this->redirectBack();
        }

        if ($user->hasRole('user')) {

            $user->removeRole('user');
            $user->assignRole('banned');

            Flash::success('User is banned.');

            return $this->redirectBack();
        }

        if ($user->hasRole('banned')) {

            $user->removeRole('banned');
            $user->assignRole('user');

            Flash::success('User is unbanned.');

            return $this->redirectBack();
        }
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    private function redirectBack()
    {
        return redirect()->back();
    }
}

app/Http/Controllers/Site/AuthorPostsController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use App\Repositories\Site\PostRepository;
use App\Repositories\Site\UserRepository;

/**
 * Class AuthorPostsController
 * @package App\Http\Controllers\Site
 */
class AuthorPostsController extends SiteController
{
    const PERPAGE = 3;

    /**
     * AuthorPostsController constructor.
     * @param PostRepository $post_rep
     * @param UserRepository $user_rep
     */
    public function __construct(PostRepository $post_rep, UserRepository $user_rep)
    {
        parent::__construct(new \App\Repositories\Site\CategoryRepository(new \App\Models\Category));

        $this->post_rep = $post_rep;
        $this->user_rep = $user_rep;

        $this->template = env('THEME').'.show_posts_author.index';
    }

    /**
     * @param $user_id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index($user_id)
    {
        $user = $this->getUser($user_id);
        $posts = $this->getPosts($user_id);
        $content_author = view(env('THEME').'.show_posts_author.author_posts')
            ->with(['posts' => $posts, 'user' => $user])->render();
        $this->vars = Arr::add($this->vars, 'content_author', $content_author);

        return $this->renderOutput();
    }

    /**
     * @param $user_id
     */
    protected function getPosts($user_id)
    {
        $search = ['user_id' => $user_id];
        $posts = $this->post_rep->allQuery($search, 'id', 'desc')->paginate(self::PERPAGE);

        return count($posts) > 0 ? $posts : abort(404);
    }

    /**
     * @param $user_id
     */
    protected function getUser($user_id)
    {
        $user = $this->user_rep->find($user_id);

        return $user ? $user : abort(404);
    }
}

app/Http/Controllers/Site/CategoryPostsController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use App\Repositories\Site\PostRepository;
use App\Repositories\Site\UserRepository;

/**
 * Class CategoryPostsController
 * @package App\Http\Controllers\Site
 */
class CategoryPostsController extends SiteController
{
    const PERPAGE = 4;

    /**
     * CategoryPostsController constructor.
     * @param PostRepository $post_rep
     * @param UserRepository $user_rep
     */
    public function __construct(PostRepository $post_rep, UserRepository $user_rep)
    {
        parent::__construct(new \App\Repositories\Site\CategoryRepository(new \App\Models\Category));

        $this->post_rep = $post_rep;
        $this->template = env('THEME').'.show_posts_category.index';
    }

    /**
     * @param $category_id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index($category_id)
    {
        $category = $this->getCategory($category_id);
        $posts = $this->getPostsCategory($category);

        $content_category = view(env('THEME').'.show_posts_category.category_posts')
            ->with(['posts' => $posts, 'category' => $category])
            ->render();
        $this->vars = Arr::add($this->vars, 'content_category', $content_category);

        return $this->renderOutput();
    }

    /**
     * @param $category
     * @return mixed
     */
    protected function getPostsCategory($category)
    {
        return $category->posts()->paginate(self::PERPAGE);
    }

    /**
     * @param $category_id
     */
    protected function getCategory($category_id)
    {
        $category = $this->cat_rep->find($category_id);

        return $category ? $category : abort(404);
    }
}

app/Http/Controllers/Site/MainController.php
<?php

namespace App\Http\Controllers\Site;

use App\Models\Post;
use App\Models\User;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use App\Repositories\Site\PostRepository;
use App\Repositories\Site\SidebarRepository;

/**
 * Class MainController
 * @package App\Http\Controllers\Site
 */
class MainController extends SiteController
{
    const PERPAGE = 5;

    /**
     * MainController constructor.
     * @param PostRepository $post_rep
     * @param SidebarRepository $sidebar_rep
     */
    public function __construct(PostRepository $post_rep, SidebarRepository $sidebar_rep)
    {
        parent::__construct(new \App\Repositories\Site\CategoryRepository(new \App\Models\Category));

        $this->post_rep = $post_rep;
        $this->sidebar_rep = $sidebar_rep;

        $this->template = env('THEME').'.main';
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $sidebar = view(env('THEME').'.parts.sidebar')->render();
        $this->vars = Arr::add($this->vars, 'sidebar', $sidebar);

        $posts = $this->getPosts();
        $content = view(env('THEME').'.parts.content')->with('posts', $posts)->render();
        $this->vars = Arr::add($this->vars, 'content', $content);

        $lastTwoPosts = $this->post_rep->all([], 'id', 'desc');
        $lastTwoPostsView = view(env('THEME').'.parts.last_two_posts')
            ->with('posts', $lastTwoPosts)->render();
        $this->vars = Arr::add($this->vars, 'lastTwoPosts', $lastTwoPostsView);

        return $this->renderOutput();
    }

    /**
     * @return mixed
     */
    protected function getPosts()
    {
        return $this->post_rep
            ->allQuery([], 'id', 'desc')
            ->with('user', 'categories')
            ->paginate(self::PERPAGE);
    }
}

app/Http/Controllers/Site/SearchPostsController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use App\Repositories\Site\PostRepository;

/**
 * Class SearchPostsController
 * @package App\Http\Controllers\Site
 */
class SearchPostsController extends SiteController
{
    const PERPAGE = 3;

    /**
     * SearchPostsController constructor.
     * @param PostRepository $post_rep
     */
    public function __construct(PostRepository $post_rep)
    {
        parent::__construct(new \App\Repositories\Site\CategoryRepository(new \App\Models\Category));

        $this->post_rep = $post_rep;

        $this->template = env('THEME').'.search_posts.index';
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index(Request $request)
    {
        $field = 'text';
        $search = $request->get('s');

        $posts = $this->getFoundPosts($field, $search, self::PERPAGE);
        $search_posts = view(env('THEME').'.search_posts.posts')
            ->with(['posts' => $posts])->render();
        $this->vars = Arr::add($this->vars, 'search_posts', $search_posts);

        return $this->renderOutput();
    }

    /**
     * @param $field
     * @param $search
     * @param $perPage
     * @return mixed
     */
    protected function getFoundPosts($field, $search, $perPage)
    {
        $posts = $this->post_rep->getLike($field, $search, $perPage);

        return $posts;
    }
}

app/Http/Controllers/Site/SinglePostController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use App\Repositories\Site\PostRepository;

/**
 * Class SinglePostController
 * @package App\Http\Controllers\Site
 */
class SinglePostController extends SiteController
{
    /**
     * SinglePostController constructor.
     * @param PostRepository $post_rep
     */
    public function __construct(PostRepository $post_rep)
    {
        parent::__construct(new \App\Repositories\Site\CategoryRepository(new \App\Models\Category));

        $this->post_rep = $post_rep;

        $this->template = env('THEME').'.show_post.index';
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index($id)
    {
        $post = $this->getPost($id);
        $content_post = view(env('THEME').'.show_post.post')->with('post', $post)->render();
        $this->vars = Arr::add($this->vars, 'content_post', $content_post);

        return $this->renderOutput();
    }

    /**
     * @param $id
     */
    protected function getPost($id)
    {
        $post = $this->post_rep->find($id);

        return $post ? $post : abort(404);
    }
}

app/Http/Controllers/Site/SiteController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Site\CategoryRepository;

/**
 * Class SiteController
 * @package App\Http\Controllers\Site
 */
class SiteController extends Controller
{
    protected $cat_rep;
    protected $post_rep;
    protected $single_post_rep;
    protected $sidebar_rep;

    protected $template;
    protected $vars = [];

    protected $bar;
    protected $contentBar;

    /**
     * SiteController constructor.
     * @param CategoryRepository $cat_rep
     */
    public function __construct(CategoryRepository $cat_rep)
    {
        $this->cat_rep = $cat_rep;
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    protected function renderOutput()
    {
        $categories = $this->getCategoriesMenu();
        $navigation = view(env('THEME').'.parts.navigation')->with('categories', $categories)->render();
        $this->vars = Arr::add($this->vars, 'navigation', $navigation);

        return view($this->template)->with($this->vars);
    }

    /**
     * @return mixed
     */
    protected function getCategoriesMenu()
    {
        return $this->cat_rep->get();
    }
}

resources/views/site/parts/content.blade.php
<div class="col-md-8 blog-main">
    
    <h3 class="pb-4 mb-4 font-italic border-bottom">
        From the Firehose
    </h3>  
    
    <div class="blog-post">    
        @foreach($posts as $post)            
            
            @if(!$post->user->hasRole('banned'))
                <a href="{{ route('single_post', $post) }}"><h4 class="blog-post-title">{{ $post->header }}</h4></a>
                <p class="blog-post-meta">
                    {{ $post->getPostDate() }} by        
                    <a href="{{ route('show_posts_author', $post->user_id) }}">{{ $post->user->name }}, </a>             
                    рубрика: {{ $post->categories->implode('name', ', ') }}
                </p>          
                <p>{{ Str::limit($post->text, 80, '... [') }}         
                    <a href="{{ route('single_post', $post) }}"><small>Read more</small></a>    
                    ]
                </p>  
            @endif
        @endforeach
    </div><!-- /.blog-post -->
    
    {{ $posts->links() }}
    
</div><!-- /.blog-main -->

resources/views/site/parts/footer.blade.php
<footer class="blog-footer">
    <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    <p>
        <a href="#top">Back to top</a>
    </p>
</footer>

resources/views/site/parts/header.blade.php
<header class="blog-header py-3" name="top">
    <div class="row flex-nowrap justify-content-between align-items-center">                    
        <div class="col-4 pt-1">
            <a class="text-muted" href="{{ route('posts.create') }}">Разместить статью</a>
        </div>
        <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{{ route('main') }}">Large</a>
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">        
            <nav class="mr-3">
                <form style="display: flex;" class="" method="GET" action="{{ route('search') }}">
                    <input name="s" class="form-control btn-sm mr-sm-2 @error('s') is-invalid @enderror" type="search" placeholder="Search" aria-label="Search" required>
                    <button class="btn btn-outline-secondary btn-sm my-2 my-sm-0" type="submit">Search</button>
                </form>
            </nav>
            
            @if(Auth::check())                                                
                <div class="dropdown">                
                    <a class="nav-link dropdown-toggle text-muted" href="#" id="dropdownMenuButton" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ Auth::user()->name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item text-muted" href="{{ route('posts.index') }}">{{ __('Your articles') }}</a>
                        <a class="dropdown-item text-muted" href="{{ route('profile.show') }}">{{ __('Profile') }}</a>
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf    
                            <a class="dropdown-item text-muted" href="{{ route('logout') }}"
                                onclick="event.preventDefault(); this.closest('form').submit();">
                                {{ __('Logout') }}
                            </a>
                        </form>
                    </div>
                </div>
            @else
                <a class="btn btn-sm btn-outline-secondary" href="{{ route('login') }}">Sign&nbsp;in</a>
                <a class="btn btn-sm btn-secondary ml-1" href="{{ route('register') }}">Sign&nbsp;up</a>
            @endif
        </div>
    </div>
</header>

resources/views/site/parts/last_two_posts.blade.php
<div class="row mb-2">    
    @set($i, 1)
    
    @foreach($posts as $post)
        @php $i++ @endphp
        
        @if($post->user->hasRole('banned'))
            @php $i-- @endphp
            @continue
        @else
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">    
                        <strong class="d-inline-block mb-2 text-primary">{{ $post->categories->implode('name', ', ') }}</strong>
                        <h3 class="mb-0">{{ $post->header }}</h3>
                        <div class="mb-1 text-muted">{{ $post->getPostDateWithoutYear() }}</div>
                        <p class="card-text mb-auto">{{ Str::limit($post->text, 110) }}</p>
                        <a href="{{ route('single_post', $post) }}" class="stretched-link">Continue reading</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                    </div>
                </div>
            </div>
        @endif
        
        @if($i > 2)
            @break
        @endif    
    @endforeach
</div>

resources/views/site/parts/navigation.blade.php
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        @foreach($categories as $category)
        
<a class="p-2 text-muted" href="{{ route('show_posts_category', $category) }}">{{ $category->name }}</a>
        
        @endforeach
    </nav>
</div>

resources/views/site/parts/sidebar.blade.php
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  
  <div class="p-4">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
      <li><a href="#">December 2013</a></li>
      <li><a href="#">November 2013</a></li>
      <li><a href="#">October 2013</a></li>
      <li><a href="#">September 2013</a></li>
      <li><a href="#">August 2013</a></li>
      <li><a href="#">July 2013</a></li>
      <li><a href="#">June 2013</a></li>
      <li><a href="#">May 2013</a></li>
      <li><a href="#">April 2013</a></li>
    </ol>
  </div>
  
  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="#">GitHub</a></li>
      <li><a href="#">Twitter</a></li>
      <li><a href="#">Facebook</a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->